NAME		=		Animal

SRC			=		WrongAnimal.cpp Animal.cpp Dog.cpp Cat.cpp WrongCat.cpp main.cpp

OBJ			=		$(SRC:.cpp=.o)

FLAG		=		-Wall -Wextra -Werror -std=c++98

.PHONY		:		all clean fclean re

all			:		$(NAME)

$(NAME)		:		$(OBJ) WrongAnimal.hpp Animal.hpp Dog.hpp Cat.hpp WrongCat.hpp
	c++ $(FLAG) $(OBJ) -o $(NAME)

clean		:
	rm -f $(OBJ)

fclean		:	clean
	rm -f $(NAME)

re			:	clean all
